In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### MNIST dataset

In [84]:
# Function to one-hot encode the target variable into the 10 classes (0-9)
# Input shape: (N,),    Output: (N, 10)
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, 10))
    one_hot_Y[np.arange(Y.size), Y] = 1
    return one_hot_Y

In [85]:
# Loading the MNIST dataset
train_data=pd.read_csv(r"./mnist_train.csv")
test_data=pd.read_csv(r"./mnist_test.csv")

# Preprocessing the data
train_data=train_data.to_numpy()    # train_data shape: (60000, 785)
test_data=test_data.to_numpy()      # test_data shape: (10000, 785)

X_train=train_data[:,1:]            # X_train shape: (60000, 784)
y_train=train_data[:,0]             # y_train shape: (60000,)
X_test=test_data[:,1:]              # X_test shape: (10000, 784)
y_test=test_data[:,0]               # y_test shape: (10000,)

X_train = X_train / 255.0           # Normalizing the data
X_test = X_test / 255.0
# X_train = X_train.T
one_hot_y_train = one_hot(y_train)  # one_hot_y_train shape: (60000, 10)
one_hot_y_test = one_hot(y_test)    # one_hot_y_test shape: (10000, 10)

In [140]:
train_data

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [8, 0, 0, ..., 0, 0, 0]], shape=(60000, 785))

#### Training on the other Boolean functions

### Task 1

In [86]:
# XOR dataset

XOR_x = np.array([[0, 0, 1, 1],
                [0, 1, 0, 1]])
XOR_y = np.array([0, 1, 1, 0])


In [87]:
# function to generate bin seq array of 5 inputs

def bin_seq(pr, BIN_dataset):
    A = [0]*pr
    temp = []
    for i in range(2**pr):
        j = 0
        k = i
        while(j < pr):
            
            if (k & 1) == 1:
                A[j] = 1
            k = (k//2)
            j += 1
        BIN_dataset.append(A)
        A = [0]*pr

input_5 = []
bin_seq(5, input_5)
input_5 = np.array(input_5)
input_5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1],
       [1, 1, 0, 1, 1],
       [0, 0, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [188]:
# Palindrome detection
def is_palindrome(X):
    i = 0
    j = len(X) - 1
    while j >= i:
        if (X[i] != X[j]):
            return False
        j -= 1
        i += 1
    return True

# majority function
def majority(X):
    cnt1 = 0
    cnt0 = 1
    for i in X:
        cnt1 += (i == 1)
        cnt0 += (i == 0)
    if cnt1 > cnt0:
        return True
    return False

# even parity function
def even_parity(X):
    cnt1 = 0
    cnt0 = 1
    for i in X:
        cnt1 += (i == 1)
        cnt0 += (i == 0)
    if cnt1 % 2 == 0:
        return True
    return False



In [189]:
# other dataset output

BIN_y = np.array([int(is_palindrome(k)) for k in input_5])
MAJ_y = np.array([int(majority(k)) for k in input_5])
EVE_y = np.array([int(even_parity(k)) for k in input_5])

print(BIN_y)
print(MAJ_y)
print(EVE_y)

[1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1]
[1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 0 1 0 1 1 0]


### Task 2

In [ ]:
# initializing parameters
def initialize_param(X, Y):
    W1 = np.random.randn(10, 784) - 0.5
    b1 = np.random.randn(10, 1) - 0.5
    W2 = np.random.randn(10, 10) - 0.5
    b2 = np.random.randn(10, 1) - 0.5
    return W1, b1, W2, b2

# sigmoid activation function
def sigmoid_func(x):
    return (1 / (1 + (np.exp(-1*x))))

def relu_func(Z):
    return np.maximum(Z, 0)

def relu_derv(Z):
    return Z > 0

def softmax(Z):
    A = np.exp(Z) / (np.sum(np.exp(Z), axis = 1).reshape(10, 1))
    # print(np.sum(A[0]))
    return A

def concat(X, n):
    X = list(X)
    X.append(n);
    X = np.array(X)
    return X.copy()

# choosing number of hidden layes as 1
def forward_prop_1(X, W1, b1, W2, b2):
    Z1 = W1.dot(X.T) + b1
    A1 = relu_func(Z1)
    # print(f"A1:: ", Z1.shape)
    Z2 = np.dot(W2, A1) + b2
    # print(Z2.shape)
    A2 = softmax(Z2)
    # print(f"Z2:: ",Z2.shape)
    return Z1, A1, Z2, A2

def sigmod_derv(Z):
    return Z * (1 - Z)

def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    dZ2 = A2 - one_hot_y_train.T
    m = 60000
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * relu_derv(Z1)
    dW1 = 1 / m * dZ1.dot(X)
    db1 = 1 / m * np.sum(dZ1)
    # print(dW1, dW2)
    return dW1, db1, dW2, db2


def update_param(W1, b1, W2, b2, dW1, dW2, db1, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

   

In [ ]:
def get_pred(A2):
    return np.argmax(A2, 0)

def accu(Y_pred, Y):
    return np.sum(Y_pred == Y) / Y.size

def gradient(X, Y, alpha, iteration):
    W1, b1, W2, b2 = initialize_param(X, Y)
    for i in range(iteration):
        Z1, A1, Z2, A2 = forward_prop_1(X, W1, b1, W2, b2)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_param(W1, b1, W2, b2, dW1, dW2, db1, db2, alpha)
        if i % 100 == 0:
            print("----------------------------------------------")
            print(f"Iteration: ", i)
            pred = get_pred(A2)
            print(pred, Y)
            print(accu(pred, Y))
            print("----------------------------------------------")
    return W1, b1, W2, b2            

In [ ]:

W1, b1, W2, b2 = gradient(X_train, y_train, 0.01, 1000)